#!/bin/sh

echo $(date) restarted >> /var/log/projects/uralsocionics/restart.log
exec chpst -u madera /home/madera/projects/uralsocionics/ENV/bin/python /home/madera/projects/uralsocionics/src/manage.py runfcgi minspare=1 maxspare=1 errlog=/var/log/projects/uralsocionics/fcgi-error.log method=prefork socket=/home/madera/projects/uralsocionics/fcgi.sock pidfile=/home/madera/projects/uralsocionics/pid daemonize=false
